# Generated by Django 3.2.6 on 2022-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createdDogWalkerProfile',
            field=models.BooleanField(default=False),
        ),
    ]
