# Generated by Django 3.2.6 on 2022-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_createddogwalkerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
