# Generated by Django 3.2.6 on 2022-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
