# Generated by Django 3.2.6 on 2022-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('usr_img', models.ImageField(upload_to='usrImgs')),
                ('email', models.EmailField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('usr_info', models.TextField()),
                ('is_available', models.BooleanField()),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('acpt_pup', models.BooleanField()),
            ],
        ),
    ]
