# Generated by Django 3.2.12 on 2022-05-12 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usr_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('min_weight', models.IntegerField(default=0)),
                ('max_weight', models.IntegerField(default=130)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('usr_info', models.TextField()),
                ('avbl_from', models.DateField()),
                ('avbl_to', models.DateField()),
                ('is_avbl', models.BooleanField(default=False)),
                ('acpt_pup', models.BooleanField()),
            ],
        ),
    ]
