# Generated by Django 3.2.12 on 2022-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalker',
            name='max_wt',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='dogwalker',
            name='min_wt',
            field=models.IntegerField(default=0),
        ),
    ]
