# Generated by Django 3.2.12 on 2022-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dogwalker',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
