# Generated by Django 3.2.12 on 2022-05-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalker',
            name='username',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
