# Generated by Django 3.2.6 on 2022-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalker',
            name='base64_img',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
