# Generated by Django 3.2.12 on 2022-03-23 16:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0002_alter_dogwalker_usr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='usr_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to='usrImgs'),
        ),
    ]
