# Generated by Django 3.2.6 on 2022-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0002_dogwalker_base64_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalker',
            name='activation_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
