# Generated by Django 3.2.12 on 2022-05-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0002_dogwalker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='max_weight',
            field=models.IntegerField(default=0),
        ),
    ]
