# Generated by Django 3.2.12 on 2022-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0002_auto_20220426_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogwalker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
