# Generated by Django 3.2.12 on 2022-04-27 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0003_dogwalker_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
