# Generated by Django 3.2.6 on 2022-05-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0003_dogwalker_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogwalker',
            name='activation_code',
        ),
    ]
