# Generated by Django 3.2.12 on 2022-05-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0003_auto_20220504_0739'),
        ('dogWalkers', '0004_alter_dogwalker_rating'),
    ]

    operations = [
    ]
