# Generated by Django 3.2.6 on 2022-05-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0004_remove_dogwalker_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogwalker',
            name='base64_img',
        ),
    ]
