# Generated by Django 3.2.12 on 2022-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogWalkers', '0005_merge_20220509_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalker',
            name='price',
            field=models.IntegerField(),
        ),
    ]
